apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    {{- include "email-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.emailServiceApi.replicaCount }}
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
        {{- include "email-processor.labels" . | nindent 8 }}
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
        - name: emailservice
          image: {{ .Values.emailServiceApi.repository }}:{{ .Values.emailServiceApi.tag }}
          resources: 
            requests:
              cpu: 4
              memory: 4Gi
            limits:
              memory: 16Gi
          ports:
            - containerPort: 8080
          env:
            - name: Azure__AzureStorageConnectionString
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: Azure__AzureStorageConnectionString
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.otelExporterOtlpEndpoint }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.emailServiceApi.otelServiceName }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: {{ .Values.env.otelResourceAttributes }}
            - name: Kafka__Bootstrap__0
              value: {{ .Values.kafka.clusterName }}-kafka-bootstrap:9092
            - name: processorService__ServiceId
              value: {{ .Values.processorService.serviceId }}
            - name: processorService__ClusterId
              value: {{ .Values.processorService.clusterId }}
            - name: Logging__LogLevel__Default
              value: Information
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value:  Information
            - name: Logging__LogLevel__Microsoft.AspNetCore.Hosting.Diagnostics
              value:  Warning
            - name: Logging__LogLevel__Microsoft.AspNetCore.Routing
              value:  Warning
            - name: ASPNETCORE_ENVIRONMENT
              value: Development

          livenessProbe:
            httpGet:
              path: /alive
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
      terminationGracePeriodSeconds: 180
