{{- include "required-repository" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    {{- include "email-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.emailServiceApi.replicaCount }}
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
        {{- include "email-processor.labels" . | nindent 8 }}
    spec:
      containers:
        - name: emailservice
          image: "{{ .Values.emailServiceApi.repository }}/{{ .Values.emailServiceApi.image }}:{{ .Values.emailServiceApi.tag }}"
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: Azure__AzureStorageConnectionString
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: connectionString
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.otelExporterOtlpEndpoint }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.emailServiceApi.otelServiceName }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: {{ .Values.env.otelResourceAttributes }}
            - name: Kafka__Bootstrap__0
              value: {{ .Values.kafka.clusterName }}-bootstrap:9092
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
