{{- if .Values.ingress.enabled -}}
{{- include "required-ssl-cert" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emailservice-api-ingress
  labels:
    {{- include "email-processor.labels" . | nindent 4 }}
  annotations:
    haproxy.org/server-ssl: 'false'
    haproxy.org/ssl-certificate: {{ .Values.ingress.annotations.sslCertificate }}
    haproxy.org/ssl-redirect: 'false'
    haproxy.org/ssl-redirect-port: '443'
spec:
  ingressClassName: haproxy
  rules:
    - host: {{ index .Values.ingress.hosts 0 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emailservice
                port:
                  number: 8080
  tls:
    - hosts:
      - {{ index .Values.ingress.hosts 0 }}
{{- end }}

---

{{- if .Values.ingress.enabled -}}
{{- include "required-ssl-cert" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emailservice-host-ingress
  labels:
    {{- include "email-processor.labels" . | nindent 4 }}
  annotations:
    haproxy.org/server-ssl: 'false'
    haproxy.org/ssl-certificate: {{ .Values.ingress.annotations.sslCertificate }}
    haproxy.org/ssl-redirect: 'false'
    haproxy.org/ssl-redirect-port: '443'
spec:
  ingressClassName: haproxy
  rules:
    - host: {{ index .Values.ingress.hosts 1 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: processorhost
                port:
                  number: 8080
  tls:
    - hosts: 
      - {{ index .Values.ingress.hosts 1 }}
{{- end }}