{{- if .Values.kafka.clusterName -}}
{{- range .Values.kafka.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    {{- include "email-processor.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ $.Values.kafka.clusterName }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
    retention.bytes: 5368709120
    delete.retention.ms: 10000
    min.cleanable.dirty.ratio: 0.01
    retention.ms: 600000

---

{{- end }}
{{- else -}}
{{- fail "kafka.clusterName is a required value" -}}
{{- end -}}