apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  replicas: {{ .Values.mailpit.replicaCount }}
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: {{ .Values.mailpit.repository }}:{{ .Values.mailpit.tag }}
          resources: 
            requests:
              cpu: 8
              memory: 4Gi
            limits:
              memory: 16Gi
          ports:
            - containerPort: 1025
            - containerPort: 8025
          env:
            - name: MP_MAX_MESSAGES
              value: "0"
            - name: MP_SMTP_AUTH_ACCEPT_ANY
              value: "true"
            - name: MP_SMTP_AUTH_ALLOW_INSECURE
              value: "true"
          livenessProbe:
            httpGet:
              path: /livez
              port: 8025
            failureThreshold: 3
            periodSeconds: 30
          
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8025
            failureThreshold: 30
            periodSeconds: 10
            
---

apiVersion: v1
kind: Service
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  selector:
    app: mailpit
  ports:
    - protocol: TCP
      port: 8025
      targetPort: 8025
      name: http
    - protocol: TCP
      port: 1025
      targetPort: 1025
      name: smtp