apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  replicas: {{ .Values.mailpit.replicaCount }}
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: {{ .Values.mailpit.repository }}:{{ .Values.mailpit.tag }}
          ports:
            - containerPort: 1025
            - containerPort: 8025
          env:
            
          livenessProbe:
            httpGet:
              path: /livez
              port: 8025
            failureThreshold: 1
            periodSeconds: 10
          
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8025
            failureThreshold: 30
            periodSeconds: 10
            
---

apiVersion: v1
kind: Service
metadata:
  name: mailpit
spec:
  selector:
    app: mailpit
  ports:
    - protocol: TCP
      port: 8025
      targetPort: 8025
      name: http
    - protocol: TCP
      port: 1025
      targetPort: 1025
      name: smtp