apiVersion: v1
kind: Service
metadata:
  name: processing-host
spec:
  selector:
    app: processing-host
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443