apiVersion: v1
kind: Service
metadata:
  name: processorhost
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: processorhost