apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    {{- include "email-processor.labels" . | nindent 4 }}
spec:
  selector:
    app: emailservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http