apiVersion: v1
kind: Service
metadata:
  name: emailservice-api
spec:
  selector:
    app: emailservice-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443