repository : REQUIRED
host: example.com

emailServiceApi:
  replicaCount: 2
  repository: emailservice
  image: 
  tag: latest
  pullPolicy: IfNotPresent
  otelServiceName: email-service-api

processorService:
  replicaCount: 3
  repository: processorhost
  tag: latest
  pullPolicy: IfNotPresent
  otelServiceName: email-service-processor
  clusterId: email-processor-poc
  serviceId: email-processor-poc

mailpit:
  replicaCount: 2
  repository: mailpit
  tag: latest
  pullPolicy: IfNotPresent

kafka:
  clusterName: email-svc-poc-kfk
  version: "3.5.2"
  replicas: 3
  topics:
  - name: outbox
    partitions: 30
    replicas: 2
  - name: template-render
    partitions: 30
    replicas: 2

kowl:
  replicaCount: 1
  repository: kwolrepo
  tag: latest
  pullPolicy: IfNotPresent  

env:
  otelExporterOtlpEndpoint: http://localhost:4317
  otelResourceAttributes: deployment.environment=development,service.namespace=EmailServicePoc,service.version=1.0.0.0-beta01

ingress:
  enabled: true
  hosts:
    - emailservice.gigya.net
    - processorhost.gigya.net
  annotations:
    sslCertificate: REQUIRED